name: gmpi
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - tqdm
  - h5py
  - jupyterlab
  - matplotlib
  - joblib
  - lz4
  - pylint
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit
  - imageio
  - imageio-ffmpeg
  - tensorboard
  - pip
  - pip:
    - setuptools
    - lpips
    - yacs
    - scikit-image
    - scikit-video
    - opencv-python
    - black
    - trimesh
    - flake8
    - flake8-bugbear
    - flake8-comprehensions
    - clean-fid
    - torch_ema
    - torch-fidelity
    - mrcfile
    - dill
    - click
    - psutil
    - lazy
    - pyspng
    - PyMCubes
